### ISSUE TITLE
errors 'force_unicode' and 'I/O operation on closed file'

### ISSUE THREAD

**Issue by nordbit** [Tivix/django-common#23] opened 2015-06-16 01:51 UTC
Trying run scaffold from docs:
```python manage.py scaffold forum --model Forum char:name```

  py3, django 1.8.2
```File "/srv/testy/lib/python3.4/site-packages/django_common/admin.py", line 12, in <module>
    from django.utils.encoding import force_unicode
ImportError: cannot import name 'force_unicode'```

py2, django 1.7.8
```  File "/srv/testy/lib/python3.4/site-packages/django_common/management/commands/scaffold.py", line 38, in handle
    scaffold.run()
  File "/srv/testy/lib/python3.4/site-packages/django_common/scaffold.py", line 730, in run
    self.create_model()
  File "/srv/testy/lib/python3.4/site-packages/django_common/scaffold.py", line 515, in create_model
    for line in self.models_file.readlines():
ValueError: I/O operation on closed file.```

**Comment by imanhodjaev** [comment] 2015-06-22 19:48
Made fixes in the pull request https://github.com/Tivix/django-common/pull/20

**Comment by imanhodjaev** [comment] 2015-06-22 19:49
I couldn't reproduce the first case with Python 3 and Django 1.8.2

**Comment by mjaworski** [comment] 2015-06-24 09:56
PR #20 merged

**Closed by mjaworski** 2015-06-24 09:56 UTC
